services:

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8087:8087"
    volumes:
      - ./.env:/app/.env
      - ./src/thunderbird_accounts:/app/thunderbird_accounts
      - ./static:/app/static
      - ./templates:/app/templates

  postgres:
    image: postgres:17
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Note: host is exposed to 5433!
    environment:
      - POSTGRES_DB=accounts
      - POSTGRES_USER=accounts
      - POSTGRES_PASSWORD=accounts
    # set shared memory limit when using docker-compose
    shm_size: 128mb

  redis:
    image: redis/redis-stack
    volumes:
      - cache:/data
    ports:
      - "6380:6379" # Redis exposed on port 6380
      - "8071:8001" # Insights exposed on port 8071

  mailpit:
    image: axllent/mailpit
    environment:
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    ports:
      - "8026:8025" # Web UI on port 8026
      - "1026:1024" # SMTP on port 1026

volumes:
  db: {}
  cache: {}
